### ISSUE TITLE
personFacetGraph and rootSearchGraph not always returning the same results

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-queries#2]
sometimes the root search query, eg http://buda1.bdrc.io:13280/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22zhi%20ba%27i%20lha%22 :

![image](https://user-images.githubusercontent.com/33383857/40923187-671f57fc-6814-11e8-821d-db31c62a65e2.png)

returns more persons than the query on persons only, eg http://buda1.bdrc.io:13280/lib/personFacetGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22zhi%20ba%27i%20lha%22 :

![image](https://user-images.githubusercontent.com/33383857/40923119-3b2c22d8-6814-11e8-8601-e4662f63d781.png)

**Comment by MarcAgate** [comment]
Fixed as of commit 7b1a34b
