### ISSUE TITLE
etext fetching

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-queries#3]
It would be good to have a query that fetches a bunch of content from etexts, and not the whole etext at once (which is too big). The request would take 3 parameters:
- the ID of the etext
- the seqNum of the first chunk to fetch
- the limit in numbers of chunks

so that the client can download like 20 chunks per 20 chunks.

**Comment by eroux** [comment]
(for the sake of convenience, it's probably easier if the third parameter is the last seqNum)

**Comment by MarcAgate** [comment]
actually, we don't have to fix the last parameter
