### ISSUE TITLE
PlaceAllAssociation improvement

### ISSUE THREAD

**Issue by MarcAgate** [BuddhistDigitalResourceCenter/lds-queries#5]
http://purl.bdrc.io/lib/placeAssocPersons?R_RES=bdr:G37 should return P264

http://purl.bdrc.io/resource/G37.ttl says:

```
bdr:TraditionTaxonomy
                   ] ,
         [ a             bdr:PlaceFounded ;
           bdo:eventWho  bdr:P264 ;
           bdo:onYear    1860
         ] ;
```

**Comment by eroux** [comment]
is `placeAssocPersons` used? I thought only `placeAllAssociations` was... (if it's not, I think this falls under #4)

**Comment by MarcAgate** [comment]
I am not sure so I maintained it... this is actually a question for @berger-n

**Comment by berger-n** [comment]
actually only `placeAllAssociations` is in use now

**Comment by berger-n** [comment]
here it is:

```
allAssocResource.arq

rootSearchGraph.arq
workFacetGraph.arq
personFacetGraph.arq

personAllAssociations.arq
placeAllAssociations.arq
topicAllAssociations.arq
workAllAssociations.arq

```

**Comment by MarcAgate** [comment]
Thanks !

**Comment by eroux** [comment]
and in iiif-presentation:

```
IIIFPres_workGraph_noItem
IIIFPres_volumeInfo
IIIFPres_itemGraph
```

**Comment by MarcAgate** [comment]
Great !

**Comment by eroux** [comment]
I think we can close this one? @MarcAgate ?

**Comment by MarcAgate** [comment]
I've done some cleanup, so unless you find some of the remaining templates irrelevant or useless, yes we can close it.
